
# config.yaml for autocorrect experiments

# General settings

current_experiment: "Question Few Shot Classification of 4 categories, GPT-4 "
experiment_description: | 
  Classfying the quality of questions using GPT, input is instructions, questions and the database schema, with GPT-4.
  The questions are classified based on four categories which are provided with examples in the prompt.
group: "autocrrect"

# dataset: "Spider"
# dataset: "BIRD"
# dataset: "BIRDFixedFinancial"
# dataset: "BIRDFixedFinancialGoldSQL"
dataset: BIRDCorrectedFinancialGoldAnnotated

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-4"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024
