
# config.yaml for text-to-SQL experiments

# General settings
current_experiment: "zero_shot_experiment"
output_dir: "/path/to/output/results"

experiments: 
  zero_shot_experiment:
    description: "Description for experiment 1"
    agent: "zero_shot"
    hyperparameters:
      prompt: "zero_shot_base_prompt"
  
  few_shot_experiment:
    description: "Description for experiment 1"
    hyperparameters:
      
    
# Domain settings
domains: 
  - financial
#  - retail_world
#  - retails
#  - car_retails

difficulties: 
  - simple
#  - moderate
#  - challenging

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024

# Agents settings
agents:
  - zero_shot:
      description: "Default LLM without any special techniques."


# Prompt Templates
prompt_templates:
    zero_shot_base_template: "Database schema in the form of CREATE_TABLE statements:
{database_schema}
-- Using valid SQLite, answer the following questions for the tables provided above. 
Question: {question}
DO NOT return anything else except the SQL statement."
