
# config.yaml for text-to-SQL experiments

# General settings

log_experiment: true

current_experiment: "gold_query_timing_experiment"
project: "text-to-sql-generation"
entity: "master-thesis-combientmix"
    
# Domain settings
domains: 
  - financial
#  - retail_world
  - retails
#  - car_retails

difficulties: 
  - simple
  - moderate
  - challenging

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024




