
# config.yaml for text-to-SQL experiments

# General settings

current_experiment: "DIN-SQL BIRD Fixed Financial"
experiment_description: "DIN-SQL agent run on our fixed financial domain"
group: "DIN SQL"

# dataset: "Spider"
# dataset: "BIRD"
# dataset: "BIRDFixedFinancial"
# dataset: "BIRDExperimentalFinancial"
dataset: "BIRDFixedFinancialGoldSQL"


project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo-16k"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024
