
# General settings

current_experiment: "Few-shot updated dev, financial only"
experiment_description: |
  Experiment rerun with the updated dev dataset that was updated 25 sep 2023. Rerunning the few_shot_experiment_6.
  Description: Sixth experiment of few-shot, giving examples from same domain (Financial), 
  taking three challenging questions, NOT skipping those questions when running the experiement.
group: "few_shot"

# dataset: "Spider"
dataset: "BIRD"

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024

  