
# General settings

current_experiment: "Few-shot corrected queries only"
experiment_description: |
  Few-shot corrected queries only
group: "few_shot"

# dataset: "Spider"
# dataset: "BIRD"
dataset: "BIRDFixedFinancialGoldSQL"

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024

  