
# General settings

current_experiment: "few-shot Spider Bank Experiment 2"
experiment_description: |
  Experiment with the whole Bank domain of the Spider dataset.
  This experiment is a few-shot experiment, where the LLM is trained on a few examples from the dataset.
  The LLM is then evaluated on the rest of the dataset.
group: "few_shot"

dataset: "Spider"
# dataset: "BIRD"

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024

  