
# General settings

current_experiment: "few_shot_experiment_8"
experiment_description: |
  Eighth experiment of few-shot, giving examples from other domains (California_schools, toxicology, card_games), taking three challenging questions.
group: "few_shot"

#dataset: "Spider"
dataset: "BIRD"

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024

  