
# config.yaml for text-to-SQL experiments

# General settings

current_experiment: "zero_shot_spider"
experiment_description: "description of experiment"
group: "zero_shot"

#dataset: "Spider"
dataset: "BIRD"

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024
