
# config.yaml for text-to-SQL experiments

# General settings

current_experiment: "Zero-shot updated dev, financial only"
experiment_description: | 
  Zero-shot agent with both bird db descriptions,create_table statements and example rows, on financial dataset only.
  This is a rerun of the zero-shot with examples row experiment but with the new dev set published 25 sep 2023./a
group: "zero_shot"

# dataset: "Spider"
dataset: "BIRD"

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024
