
# config.yaml for text-to-SQL experiments

# General settings

current_experiment: "Zero-shot corrected financial, CREATE_TABLE statements and BIRD schema, NO HINTS"
experiment_description: | 
  Zero-shot agent with BIRD descriptions + CREATE_TABLE statements but without hints on corrected financial dataset
# Zero-shot agent with both bird db descriptions,create_table statements and example rows, on financial dataset with corrected gold queries only.
group: "zero_shot"

# dataset: "Spider"
# dataset: "BIRD"
dataset: "BIRDFixedFinancial"
# dataset: "BIRDFixedFinancialGoldSQL"

project: "text-to-sql-generation"
entity: "master-thesis-combientmix"

# LLM settings
llm_settings:
  model: "gpt-3.5-turbo"
  temperature: 0
  request_timeout: 60
  token_limit: 4096
  max_response_length: 1024
